#请复制该文件复制到jar包根目录下配置好相关参数后运行程序

#chatgpt_api通过OpenAI官网获取：https://platform.openai.com/account/api-keys
chatgpt_api: 'xxxxxxxxxxxxxx'

#telegram_bot_token通过Telegram机器人@BotFather获取：https://t.me/BotFather
telegram_bot_token: 'xxxxxxxxxxxxxx'
#白名单：只有白名单内的用户才能使用机器人，默认*，代表所有用户都能使用，内容为用户的Telegram ID，可通过@userinfobot获取
whitelist:
  - '*'
#不是白名单telegram_bot提示消息
not_whitelist_msg: '你不在白名单内，无法使用机器人'

